apiVersion: v1
kind: PersistentVolume
metadata:
  name: "hdd-ext"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "2000Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/hdd"