apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media"
  name: "hdd-ext"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "2000Gi"
