replicaCount: 1

image:
  repository: linuxserver/lidarr
  tag: arm32v7-latest # ARM image
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

volumes:
  - name: media-ssd
    persistentVolumeClaim:
      claimName: "media-ssd" 
  - name: hdd-ssd
    persistentVolumeClaim:
      claimName: "hdd-ssd"
  - name: hdd-ext
    persistentVolumeClaim:
      claimName: "hdd-ext" 

volumeMounts:
  - name: media-ssd
    mountPath: "/config"
    subPath: "configs/lidarr" 
  - name: hdd-ext
    mountPath: "/downloads/transmission"
    subPath: "downloads/transmission"
  - name: hdd-ssd
    mountPath: "/Musique"
    subPath: Musique


